version: 2.1

orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@3.1.4
  ansible-playbook: orbss/ansible-playbook@0.0.5

jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yml

  cfn_execute:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - run:
          name: token and deploy
          command: |
            # use the OpenID Connect token to obtain AWS credentials
            read -r AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN \<<< \
              $(aws sts assume-role-with-web-identity \
               --role-arn ${AWS_ROLE_ARN} \
               --role-session-name "CircleCI-${CIRCLE_WORKFLOW_ID}-${CIRCLE_JOB}" \
               --web-identity-token $CIRCLE_OIDC_TOKEN \
               --duration-seconds 3600 \
               --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' \
               --output text)
            export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
            # interact with AWS
            aws --no-cli-pager sts get-caller-identity
            # CloudFormation deploy
            aws cloudformation deploy \
            --stack-name lecture13 \
            --template-file cloudformation/cfn_ansible.yml \

  ansible_execute:
    executor: ansible-playbook/default
    steps:
      - checkout
      - ansible-playbook/install
      - add_ssh_keys:
          fingerprints:
            - ae:d0:44:42:78:9e:a0:2a:d5:19:25:e5:6c:36:5f:6d
            # Want this environment variance..
      # - run:
      #     name: ansible ping
      #     command: |
      #       ansible -i ansible/inventory --private-key ~/Documents/SE/RaiseTech/AWS-13/lecture13_target.pem -u ec2-user -m ping 54.249.136.97
      - ansible-playbook/playbook:
          playbook: ansible/playbook.yml
          playbook-options: "-i ansible/inventory -u ec2-user"

workflows:
  lecture13:
    jobs:
      - cfn-lint
      - cfn_execute:
          requires: 
            - cfn-lint
          context: lecture13
          # Successfully checked Failed in CircleCI if no context!
      - ansible_execute:
          requires:
            - cfn_execute
          context: lecture13
