version: 2.1

orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@3.1.4

jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yml

  cloudformation_deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - run:
          name: token
          command: |
            # use the OpenID Connect token to obtain AWS credentials
            read -r AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN \<<< \
              $(aws sts assume-role-with-web-identity \
               --role-arn ${AWS_ROLE_ARN} \
               --role-session-name "CircleCI-${CIRCLE_WORKFLOW_ID}-${CIRCLE_JOB}" \
               --web-identity-token $CIRCLE_OIDC_TOKEN \
               --duration-seconds 3600 \
               --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' \
               --output text)
            export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
            # interact with AWS
            aws --no-cli-pager sts get-caller-identity
      - run:
          name: cfn deploy
          command: |
            # CloudFormation deploy
            aws cloudformation deploy \
            --stack-name lecture13 \
            --template-file ./cloudformation/cfn_ansible.yml \

  # cloudformation_deploy:
  #   executor: aws-cloudformation/default
  #   steps:
  #     - checkout
  #     - aws-cloudformation/deploy:
  #         aws-access-key-id: AWS_ACCESS_KEY_ID
  #         aws-secret-access-key: AWS_SECRET_ACCESS_KEY
  #         aws-region: AWS_DEFAULT_REGION
  #         stack-name: lecture13
  #         template-file-path: cloudformation/cfn_ansible.yml

workflows:
  raisetech-sample:
    jobs:
      - cfn-lint
  lecture13:
    jobs:
      - cloudformation_deploy
          # context: lecture13

      # - cloudformation_deploy:
      #     requires:
      #       - aws-cli
      #     context:
      #       - lecture13